### ISSUE TITLE
as a user i can create account through self-registration portal

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/cats-core#1]
utamanya hanya mengisikan `username`, `email`, dan `password` (mungkin ada field tambahan lainnya seperti `name`, dsb)

- [x] fitur registrasi dan autentikasi user

**Comment by afrastgeek** [comment]
@YudhaWork033 , apa issue ini sudah selesai?
saya lihat sudah di implement fitur auth laravel di bcdac2f61687bafa1ca4834d26d95d051a72f011

**Comment by YudhaWork033** [comment]
@afrastgeek,  itu untuk login dan register user baru udh bisa mas.  Tpi blom ad validasi rolenya.  Lg on progress rolenya.  

Jdi setiap user baru regitrasi.  Dia akan insert default ke table role.

**Comment by afrastgeek** [comment]
kalau begitu karena issue ini sudah solve, akan saya tutup.

selanjutnya diskusi berkaitan dengan user role dibahas di #3
