### ISSUE TITLE
migration educations, works, courses, tests, organizationals

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/cats-core#10]
semua table ini adalah me link antara organization <--> profile
atau memiliki relasi dengan:
- `profiles` melalui `profile_id`
- `organizations` melalui `organization_id`

### To Do
- [x] `educations` table

- [x] `works` table

- [x] `courses` table

- [x] `tests` table

- [x] `organizationals` table

---

- [x]  rename tabel database supaya dalam bentuk jamak

---

To-Do

- [x] add nullable to fields

**Comment by afrastgeek** [comment]
perlu menunggu #5 selesai terlebih dahulu

**Comment by YudhaWork033** [comment]
@Team,

sudah dipush, mohon dikoreksi ya.

![4](https://user-images.githubusercontent.com/38399980/39674685-4ee4cfd6-5104-11e8-8d78-4cea67bd18a8.PNG)

**Comment by renowijoyo** [comment]
@YudhaWork033 nama table semuanya jamak. work , education, role. harus jadi works, educations, & roles

**Comment by YudhaWork033** [comment]
Ok mas

**Comment by renowijoyo** [comment]
ini baru saya update ya migration scrip sama modelnya supaya jamak semua. [https://github.com/gamantha/cats-core/commit/4558cd33154606cc9796a17056d573249cc861f9](url)

**Comment by renowijoyo** [comment]
add nullable to fields

**Comment by afrastgeek** [comment]
update by @YudhaWork033 on #28

**Comment by renowijoyo** [comment]
addedd more nullable & fix organitation_id di tests
