### ISSUE TITLE
Create Migration Role and Menu

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/cats-core#3]
- [x] menambahkan role secara otomatis ke setiap user yang mendaftar

**Comment by YudhaWork033** [comment]
On progress

**Comment by renowijoyo** [comment]
ini hanya create migration untuk role dan menu atau sama yg lain juga ya mas @YudhaWork033

**Comment by YudhaWork033** [comment]
*menu segera dilakukan

saya buat migration sama logicnya mas.

jadi ketika dia login sebagai 
user01 -> maka akan menampilkan home user01 -> role menu 01
user02 -> maka akan menampilkan home user01 -> role menu 02 (mungkin ini level lebih diatas user
![1](https://user-images.githubusercontent.com/38399980/39660418-79455fc8-4ff3-11e8-8af0-4992c1384378.PNG)
)

**Comment by YudhaWork033** [comment]
untuk issue ini, sudah selesai y.

mohon dikoreksi.

![2](https://user-images.githubusercontent.com/38399980/39674184-de576230-50fc-11e8-8a84-03779db0290c.PNG)

klo sudah ok, biar saya close.

**Comment by renowijoyo** [comment]
nama role & menu dijadikan roles & menus
[https://github.com/gamantha/cats-core/commit/4558cd33154606cc9796a17056d573249cc861f9](url)

**Comment by renowijoyo** [comment]
update logic menu untuk include role_type dan role_name dari table ROLES

**Comment by YudhaWork033** [comment]
Klo menu tidak return hasil maunya menunya dikosongin kyk sekarang atau gmn mas? 

Update logic menu itu validasinya seperti apa y mas? 
Tolong dibantu samplenya y mas.  Soalnya kmren sy hny ubah di logic di contrller home aj.  Buat check ke db menu dan role

**Comment by renowijoyo** [comment]
table menu harus ditambah role_name

**Comment by renowijoyo** [comment]
logic buat menu di homecontroller nya belum ya. bikin untuk 2 ini saja dulu:
site:admin
site:user

**Comment by YudhaWork033** [comment]
![1](https://user-images.githubusercontent.com/38399980/39923229-006710d8-554d-11e8-8388-ef25641ce8b1.JPG)
![2](https://user-images.githubusercontent.com/38399980/39923245-0b586816-554d-11e8-8cc8-324517c3174c.JPG)
![3](https://user-images.githubusercontent.com/38399980/39923254-0fff0668-554d-11e8-8f7f-4efcd3fd89e1.JPG)

![4](https://user-images.githubusercontent.com/38399980/39923287-41134606-554d-11e8-8e98-b851a794849b.JPG)


saya ubah codenya ya mas, supaya role dan menu bisa dipakai sama kelas yang lain jg. :)

**Comment by YudhaWork033** [comment]
closed
