### ISSUE TITLE
Create migration profiles

### ISSUE THREAD

**Issue by renowijoyo** [gamantha/cats-core#5]
Edit (afr) on reopen:

- [x] lengkapi tabel `profiles` dengan menambahkan kolom `religion` dan `nationality`

- [ ] rename kolom `User_id` di tabel `map_profile_user` menjadi `user_id` (lowercase)

**Comment by afrastgeek** [comment]
@renowijoyo issue ini dimaksudkan untuk pembuatan migration **user profile** atau **organization profile**?

**Comment by YudhaWork033** [comment]
ini migration yang mana ya ? buat migratation table dan crud profile mksdnya ?

**Comment by YudhaWork033** [comment]
ini bukan ya mas maksdnya.
![3](https://user-images.githubusercontent.com/38399980/39674599-130dd364-5103-11e8-92fe-d01306dc2383.PNG)

**Comment by YudhaWork033** [comment]
Siap mas

**Comment by YudhaWork033** [comment]
On Checking Mas @afrastgeek @renowijoyo @putrastti

**Comment by YudhaWork033** [comment]
Point 1. Iya mas, sy salah. Baru tau tadi. 
Poin 2. Ikut perintah aja mas, kmeren sudah diskusi ttg masalah pivot ni dengan mas reno. @renowijoyo

**Comment by afrastgeek** [comment]
@YudhaWork033 jadinya direname saja mas

**Comment by YudhaWork033** [comment]
Ok mas,  belum pernah pake pivot sih. Biar sy coba.

**Comment by YudhaWork033** [comment]
1. profile_user sudah dicreate.
2. untuk table profiles sepertinya udh di handle sama mas reno untuk yang nationality.

*jika yang nulable ingin diset di lv database, mohon dibantu untuk infonya (ditable mana aja). :)

mohon dicek kembali untuk task ini, sebelum di merge.

**Comment by YudhaWork033** [comment]
Team, barusan saya ngepush dan merge lagi ya. tologn dibantu check
![6](https://user-images.githubusercontent.com/38399980/39847736-53308216-542d-11e8-9da4-7dd616de18b3.PNG)

**Comment by renowijoyo** [comment]
sudah ditambah nullable & remove map_profile_user
